/**
 * Game State Machine States
 */

export const GAME_STATES = {
  // Lobby States
  WAITING_FOR_PLAYERS: 'WAITING_FOR_PLAYERS',
  
  // Dealing States
  DEALING_FIRST_8: 'DEALING_FIRST_8',
  DEALING_REMAINING_6: 'DEALING_REMAINING_6',
  
  // Pre-Game States
  CARD_EXCHANGE: 'CARD_EXCHANGE',
  
  // Playing States
  PLAYING: 'PLAYING',
  PLAYER_TURN: 'PLAYER_TURN',
  BOMB_WINDOW: 'BOMB_WINDOW',
  WISH_ACTIVE: 'WISH_ACTIVE',
  DRAGON_GIVE: 'DRAGON_GIVE',
  
  // End States
  ROUND_END: 'ROUND_END',
  GAME_OVER: 'GAME_OVER'
};

// State Transitions (für Validierung)
export const VALID_TRANSITIONS = {
  [GAME_STATES.WAITING_FOR_PLAYERS]: [GAME_STATES.DEALING_FIRST_8],
  [GAME_STATES.DEALING_FIRST_8]: [GAME_STATES.DEALING_REMAINING_6],
  [GAME_STATES.DEALING_REMAINING_6]: [GAME_STATES.CARD_EXCHANGE],
  [GAME_STATES.CARD_EXCHANGE]: [GAME_STATES.PLAYING],
  [GAME_STATES.PLAYING]: [
    GAME_STATES.PLAYER_TURN,
    GAME_STATES.BOMB_WINDOW,
    GAME_STATES.WISH_ACTIVE,
    GAME_STATES.DRAGON_GIVE,
    GAME_STATES.ROUND_END
  ],
  [GAME_STATES.PLAYER_TURN]: [GAME_STATES.PLAYING, GAME_STATES.BOMB_WINDOW],
  [GAME_STATES.BOMB_WINDOW]: [GAME_STATES.PLAYING, GAME_STATES.PLAYER_TURN],
  [GAME_STATES.WISH_ACTIVE]: [GAME_STATES.PLAYING],
  [GAME_STATES.DRAGON_GIVE]: [GAME_STATES.PLAYING],
  [GAME_STATES.ROUND_END]: [GAME_STATES.DEALING_FIRST_8, GAME_STATES.GAME_OVER],
  [GAME_STATES.GAME_OVER]: []
};

